# fly.toml app configuration file generated for divine-mountain-3508 on 2023-05-24T04:49:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "divine-mountain-3508"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "uv run python manage.py shell"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "uv run python manage.py migrate"

[env]
  DJANGO_SETTINGS_MODULE = "triviagame.settings"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [http_service.http_options]
    idle_timeout = 600

# health checks come with an incorrect HTTP_HOST header
# (an IPv4 address), probably due to something with https/http.
# turning them off for now.
#
# [[http_service.checks]]
#   interval = "30s"
#   timeout = "2s"
#   grace_period = "5s"
#   restart_limit = 0
#   path = "/healthcheck/"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
