# Generated by Django 4.1.2 on 2022-10-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_add_host_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamehostpermissions',
            options={'verbose_name': 'Host perms', 'verbose_name_plural': 'Host perms'},
        ),
    ]
