# Generated by Django 3.2.9 on 2021-12-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviagame', '0002_better_sorts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='ensure_unique_team_names'),
        ),
    ]
