# Generated by Django 3.2.9 on 2021-11-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['game', 'order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['page', 'order']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['game', 'name']},
        ),
    ]
