# Generated by Django 4.0 on 2021-12-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_team_ensure_unique_team_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hostkey',
        ),
    ]
