# Generated by Django 4.1.2 on 2022-10-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_move_page_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='open',
        ),
    ]
