# Generated by Django 4.1.2 on 2022-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_open_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
