# Generated by Django 4.1.2 on 2022-10-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_smoosh_team_members_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-last_edit_time']},
        ),
        migrations.AddField(
            model_name='game',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
