# Generated by Django 5.0.4 on 2024-09-18 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_add_hosting_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='possible_points',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
