# Generated by Django 5.0.4 on 2024-10-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_multi_point_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
