# Generated by Django 5.2.5 on 2025-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_page_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.IntegerField(choices=[(0, 'Closed'), (1, 'Accepting Teams'), (2, 'No New Teams')], default=0),
        ),
    ]
