# Generated by Django 5.2.5 on 2025-09-04 20:57

from django.db import migrations


# When this migration runs, GameState looks like this:
#
#   class GameState(models.IntegerChoices):
#       CLOSED = 0          # game can't be accessed
#       ACCEPTING_TEAMS = 1 # game is open, new teams can register
#       NO_NEW_TEAMS = 2    # game is open, only existing teams can access

def move_open_to_state(apps, schema_editor):
    Game = apps.get_model('game', 'Game')
    for game in Game.objects.all():
        # False => 0 (CLOSED)
        # True  => 1 (ACCEPTING_TEAMS)
        game.state = 1 if game.open else 0
        game.save()


def move_state_to_open(apps, schema_editor):
    # NOTE: this is destructive in the sense that ACCEPTING_TEAMS and
    # NO_NEW_TEAMS both get mapped to True. If the migration is later
    # reapplied forwards, True gets mapped to ACCEPTING_TEAMS only.
    Game = apps.get_model('game', 'Game')
    for game in Game.objects.all():
        # 0 (CLOSED)           => False
        # 1 (ACCEPTING_TEAMS)  => True
        # 2 (NO_NEW_TEAMS)     => True
        game.open = bool(game.state)
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_introduce_game_state'),
    ]

    operations = [
        migrations.RunPython(move_open_to_state, move_state_to_open),
    ]
