# Generated by Django 5.2.5 on 2025-09-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_move_game_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='open',
        ),
    ]
