# Generated by Django 6.0 on 2025-12-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_game_open_boolean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-last_edit_time'], 'permissions': [('host_game', 'Host game')]},
        ),
    ]
