# Generated by Django 6.0 on 2026-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hide_questions',
            field=models.BooleanField(default=True),
        ),
    ]
